base_url: "https://www.comfort-gifts.com/"
supplier: "Comfort Gifts"
use_dynamic: false
sku_url_regex: '/(\d+)-'

# URL Patterns
product_url_patterns:
  - "/promotional-pens/"
  - "/PROMOTION-BAGS"
  - "/promotion-gadgets-Technology"
  - "/eco_products"
  - "/new_products"
  - "/home-and-vacation"
  - "/textile-and-clothing"
  - "/tools-flashlights-keychains"
  - "/office"
  - "/car_accessories"
  - "/medical_promo_products"
  - "/made-in-israel"
  - "/clearance"
  
category_url_patterns:
  - "/promotional-pens"
  - "/PROMOTION-BAGS"
  - "/promotion-gadgets-Technology"
  - "/eco_products"
  - "/new_products"
  - "/home-and-vacation"
  - "/textile-and-clothing"
  - "/tools-flashlights-keychains"
  - "/office"
  - "/car_accessories"
  - "/medical_promo_products"
  - "/made-in-israel"
  - "/clearance"

# Selectors
selectors:
  title: "title"
  description: "#tab-description"
  images: "a.popup-image img::src" # Expects list
  # main_image: "a.popup-image img::src" # First one
  sku: '#content li :: regex:^קוד מוצר:\s*(.*)' # Try to match from text logic if possible, or fallback

