base_url: "https://www.zeus.co.il/"
sitemap_url: "http://www.zeus.co.il/sitemap.xml"
supplier: "Zeus"
use_dynamic: false 
num_workers: 2
sku_url_regex: '(?:^|/)(\d+)[^/]*$' # Not strictly used if we extract from page

allowed_domains:
  - "www.zeus.co.il"
  - "zeus.co.il"

# URL Patterns
product_url_patterns:
  - "/product/"
  
category_url_patterns:
  - "/catalog/"
  - "/category/"

# Selectors
selectors:
  title: "h1.product_title"
  description: ".product_body"
  images: ".lightbox a.lightbox_group::href"
  sku: 'span.product_makat :: regex:מק"ט:\s*(.*)'
  # price: ".price" # Placeholder, likely not identifying anything as prices are hidden
